/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Shelf API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ErrorModel,
  LoginInputBody,
  LoginOutputBody,
  RegisterAccountInputBody,
  RegisterAccountResponseBody
} from './model';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;

export type loginResponse200 = {
  data: LoginOutputBody
  status: 200
}

export type loginResponse401 = {
  data: ErrorModel
  status: 401
}

export type loginResponse422 = {
  data: ErrorModel
  status: 422
}

export type loginResponse500 = {
  data: ErrorModel
  status: 500
}

export type loginResponseSuccess = (loginResponse200) & {
  headers: Headers;
};
export type loginResponseError = (loginResponse401 | loginResponse422 | loginResponse500) & {
  headers: Headers;
};

export type loginResponse = (loginResponseSuccess | loginResponseError)

export const getLoginUrl = () => {




  return `/api/v1/auth/login`
}

/**
 * @summary Log in
 */
export const login = async (loginInputBody: NonReadonly<LoginInputBody>, options?: RequestInit): Promise<loginResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginInputBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: loginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as loginResponse
}



export type registerAccountResponse201 = {
  data: RegisterAccountResponseBody
  status: 201
}

export type registerAccountResponse409 = {
  data: ErrorModel
  status: 409
}

export type registerAccountResponse422 = {
  data: ErrorModel
  status: 422
}

export type registerAccountResponse500 = {
  data: ErrorModel
  status: 500
}

export type registerAccountResponseSuccess = (registerAccountResponse201) & {
  headers: Headers;
};
export type registerAccountResponseError = (registerAccountResponse409 | registerAccountResponse422 | registerAccountResponse500) & {
  headers: Headers;
};

export type registerAccountResponse = (registerAccountResponseSuccess | registerAccountResponseError)

export const getRegisterAccountUrl = () => {




  return `/api/v1/auth/register`
}

/**
 * Create a Shelf account using an email and password.
 * @summary Register an account
 */
export const registerAccount = async (registerAccountInputBody: NonReadonly<RegisterAccountInputBody>, options?: RequestInit): Promise<registerAccountResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
const res = await fetch(getRegisterAccountUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(registerAccountInputBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: registerAccountResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as registerAccountResponse
}
