/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Shelf API
 * OpenAPI spec version: 1.0.0
 */
import type { AccountResponse } from './accountResponse';

export interface LoginOutputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  account: AccountResponse;
}
