/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Shelf API
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterAccountInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** The email address of the account */
  email: string;
  /** The password of the account */
  password: string;
}
