/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Shelf API
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterAccountResponseBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** The ID of the account */
  id: string;
}
