// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type RegisterRequest = {
    email: string;
    /**
     * Must contain letters and digits and must not contain the email.
     */
    password: string;
};

export type RegisterResponse = {
    id: string;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type RefreshRequest = {
    refresh_token: string;
};

export type TokenResponse = {
    access_token: string;
    refresh_token: string;
};

export type ProfileResponse = {
    id: string;
    email: string;
    created_at: string;
};

export type UpdateProfileRequest = {
    email: string;
};

export type ErrorResponse = {
    error: string;
};

export type RegisterUserData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/register';
};

export type RegisterUserErrors = {
    /**
     * Invalid request body or validation error
     */
    400: ErrorResponse;
    /**
     * Email is already taken
     */
    409: ErrorResponse;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
    /**
     * User created
     */
    201: RegisterResponse;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/login';
};

export type LoginErrors = {
    /**
     * Invalid request body or validation error
     */
    400: ErrorResponse;
    /**
     * Missing, invalid, expired or revoked JWT
     */
    401: ErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Access and refresh tokens
     */
    200: TokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RefreshTokensData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/refresh';
};

export type RefreshTokensErrors = {
    /**
     * Invalid request body or validation error
     */
    400: ErrorResponse;
    /**
     * Missing, invalid, expired or revoked JWT
     */
    401: ErrorResponse;
};

export type RefreshTokensError = RefreshTokensErrors[keyof RefreshTokensErrors];

export type RefreshTokensResponses = {
    /**
     * New access and refresh tokens
     */
    200: TokenResponse;
};

export type RefreshTokensResponse = RefreshTokensResponses[keyof RefreshTokensResponses];

export type LogoutData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/logout';
};

export type LogoutErrors = {
    /**
     * Missing, invalid, expired or revoked JWT
     */
    401: ErrorResponse;
    /**
     * Internal server error
     */
    500: ErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Tokens revoked
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/profile';
};

export type GetProfileErrors = {
    /**
     * Missing, invalid, expired or revoked JWT
     */
    401: ErrorResponse;
    /**
     * User not found
     */
    404: ErrorResponse;
};

export type GetProfileError = GetProfileErrors[keyof GetProfileErrors];

export type GetProfileResponses = {
    /**
     * Current user profile
     */
    200: ProfileResponse;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type UpdateProfileData = {
    body: UpdateProfileRequest;
    path?: never;
    query?: never;
    url: '/api/v1/users/profile';
};

export type UpdateProfileErrors = {
    /**
     * Invalid request body or validation error
     */
    400: ErrorResponse;
    /**
     * Missing, invalid, expired or revoked JWT
     */
    401: ErrorResponse;
    /**
     * User not found
     */
    404: ErrorResponse;
    /**
     * Email is already taken
     */
    409: ErrorResponse;
};

export type UpdateProfileError = UpdateProfileErrors[keyof UpdateProfileErrors];

export type UpdateProfileResponses = {
    /**
     * Updated user profile
     */
    200: ProfileResponse;
};

export type UpdateProfileResponse = UpdateProfileResponses[keyof UpdateProfileResponses];
